# name: nightly-images
# on:
#   workflow_dispatch:
#   push:

# jobs:

#   pipeline:
#     uses: ./.github/workflows/build.yaml

name: Github Action For
on:
  workflow_dispatch:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.ref_name }}
      - uses: actions/checkout@v4
        with:
          ref: 'main'
     
