# name: nightly-images
# on:
#   workflow_dispatch:
#   push:

# jobs:

#   pipeline:
#     uses: ./.github/workflows/build.yaml

name: action
on:
  push:
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.repository_owner }}
      - uses: actions/checkout@v4
        with:
          ref: 'main'
     
